http_error = {
    400: 'Bad Request Error',
    401: 'Unauthorized',
    402: 'Payment Required',
    403: 'Forbidden',
    404: 'Not Found',
    405: 'Method Not Allowed',
    406: 'Not Acceptable',
    407: 'Proxy Authentication Required',
    408: 'Request Timeout',
    409: 'Conflict',
    410: 'Gone',
    411: 'Length Required',
    412: 'Precondition Failed',
    413: 'Request Entity Too Large',
    414: 'Request-URI Too Large',
    415: 'Unsupported Media Type',
    416: 'Requested Range Not Satisfiable',
    417: 'Exception Failed',
    500: 'Internal Server Error',
    501: 'Not Implemented',
    502: 'Bad Gateway',
    503: 'Service Unavailable',
    504: 'Gateway Timeout',
    505: 'HTTP Version Not Supported'
}

# https://en.wikipedia.org/wiki/ID3
music_genre = {
    "00": "Blues",
    "01": "Classic Rock",
    "02": "Country",
    "03": "Dance",
    "04": "Disco",
    "05": "Funk",
    "06": "Grunge",
    "07": "Hip-Hop",
    "08": "Jazz",
    "09": "Metal",
    "10": "New Age",
    "11": "Oldies",
    "12": "Other",
    "13": "Pop",
    "14": "R&B",
    "15": "Rap",
    "16": "Reggae",
    "17": "Rock",
    "18": "Techno",
    "19": "Industrial",
    "20": "Alternative",
    "21": "Ska",
    "22": "Death Metal",
    "23": "Pranks",
    "24": "Soundtrack",
    "25": "Euro-Techno",
    "26": "Ambient",
    "27": "Trip-Hop",
    "28": "Vocal",
    "29": "Jazz+Funk",
    "30": "Fusion",
    "31": "Trance",
    "32": "Classical",
    "33": "Instrumental",
    "34": "Acid",
    "35": "House",
    "36": "Game",
    "37": "Sound Clip",
    "38": "Gospel",
    "39": "Noise",
    "40": "Alternative Rock",
    "41": "Bass",
    "43": "Punk",
    "44": "Space",
    "45": "Meditative",
    "46": "Instrumental Pop",
    "47": "Instrumental Rock",
    "48": "Ethnic",
    "49": "Gothic",
    "50": "Darkwave",
    "51": "Techno-Industrial",
    "52": "Electronic",
    "53": "Pop-Folk",
    "54": "Eurodance",
    "55": "Dream",
    "56": "Southern Rock",
    "57": "Comedy",
    "58": "Cult",
    "59": "Gangsta",
    "60": "Top 40",
    "61": "Christian Rap",
    "62": "Pop/Funk",
    "63": "Jungle",
    "64": "Native US",
    "65": "Cabaret",
    "66": "New Wave",
    "67": "Psychadelic",
    "68": "Rave",
    "69": "Showtunes",
    "70": "Trailer",
    "71": "Lo-Fi",
    "72": "Tribal",
    "73": "Acid Punk",
    "74": "Acid Jazz",
    "75": "Polka",
    "76": "Retro",
    "77": "Musical",
    "78": "Rock & Roll",
    "79": "Hard Rock",
    # above all are in standard genre list in ID3v1
    # Other genres are not include.
}
